### ISSUE TITLE
Unable to find requested simulator (iOS) without --target flag

### ISSUE THREAD

**Issue by svenemtell** [apache/cordova-paramedic#264]
# Bug Report

## Problem

I get this error when running cordova-paramedic without the `--target` flag.
```
Unable to find requested simulator, falling back to the first available!
Error: Cannot read properties of undefined (reading 'trim')
```

### Environment, Platform, Device
macOS 13.5.2 (Apple Silicon)
Xcode 14.3.1

### Version information
cordova 12.0.0
cordova-ios 7.0.1
ios-deploy 1.12.2
cordova-paramedic commit 65905f9 (latest github:apache/cordova-paramedic including #261)

**Comment by breautek** [comment]
I've encountered this recently too, a workaround right now is launching the simulator before running paramedic.

This can be done either through XCode graphically, or if you're working on CI, you can use:

```
xcrun simctl boot <UUID>
```

You can use xcrun simctl list to list available devices along with their UUID.

If you're operating in command line but still on a graphical system, `xcrun simctl` simply boots the simulator. To launch the Mac app to view the simulator you can use `open -a Simulator`. The boot command should be sufficient for paramedic though... but I haven't explicitly tested this myself.

I've added the bug label so that we can keep track and correct the root issue though.

**Comment by svenemtell** [comment]
Thanks!
As of now I just specify a target (using _--target_) as a workaround.
